# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cardsynthesis.ui'
#
# Created: Sun Dec 23 12:00:23 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_cardSynthesis(object):
    def setupUi(self, cardSynthesis):
        cardSynthesis.setObjectName(_fromUtf8("cardSynthesis"))
        cardSynthesis.resize(467, 515)
        self.verticalLayout_3 = QtGui.QVBoxLayout(cardSynthesis)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_6 = QtGui.QLabel(cardSynthesis)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.weaponLevelBox = QtGui.QSpinBox(cardSynthesis)
        self.weaponLevelBox.setMinimum(1)
        self.weaponLevelBox.setObjectName(_fromUtf8("weaponLevelBox"))
        self.horizontalLayout.addWidget(self.weaponLevelBox)
        self.weaponAtoBox = QtGui.QSpinBox(cardSynthesis)
        self.weaponAtoBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.weaponAtoBox.setSuffix(_fromUtf8(""))
        self.weaponAtoBox.setMaximum(15000)
        self.weaponAtoBox.setObjectName(_fromUtf8("weaponAtoBox"))
        self.horizontalLayout.addWidget(self.weaponAtoBox)
        self.weaponRarityBox = QtGui.QComboBox(cardSynthesis)
        self.weaponRarityBox.setObjectName(_fromUtf8("weaponRarityBox"))
        self.weaponRarityBox.addItem(_fromUtf8(""))
        self.weaponRarityBox.addItem(_fromUtf8(""))
        self.weaponRarityBox.addItem(_fromUtf8(""))
        self.weaponRarityBox.addItem(_fromUtf8(""))
        self.weaponRarityBox.addItem(_fromUtf8(""))
        self.weaponRarityBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.weaponRarityBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(cardSynthesis)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.weaponNBox = QtGui.QSpinBox(cardSynthesis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weaponNBox.sizePolicy().hasHeightForWidth())
        self.weaponNBox.setSizePolicy(sizePolicy)
        self.weaponNBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.weaponNBox.setAutoFillBackground(False)
        self.weaponNBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.weaponNBox.setObjectName(_fromUtf8("weaponNBox"))
        self.gridLayout.addWidget(self.weaponNBox, 0, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(cardSynthesis)
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(cardSynthesis)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.weaponRBox = QtGui.QSpinBox(cardSynthesis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weaponRBox.sizePolicy().hasHeightForWidth())
        self.weaponRBox.setSizePolicy(sizePolicy)
        self.weaponRBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.weaponRBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.weaponRBox.setObjectName(_fromUtf8("weaponRBox"))
        self.gridLayout.addWidget(self.weaponRBox, 1, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(cardSynthesis)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(cardSynthesis)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.weaponRRBox = QtGui.QSpinBox(cardSynthesis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weaponRRBox.sizePolicy().hasHeightForWidth())
        self.weaponRRBox.setSizePolicy(sizePolicy)
        self.weaponRRBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.weaponRRBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.weaponRRBox.setObjectName(_fromUtf8("weaponRRBox"))
        self.gridLayout.addWidget(self.weaponRRBox, 2, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(cardSynthesis)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(cardSynthesis)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.weaponSBox = QtGui.QSpinBox(cardSynthesis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weaponSBox.sizePolicy().hasHeightForWidth())
        self.weaponSBox.setSizePolicy(sizePolicy)
        self.weaponSBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.weaponSBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.weaponSBox.setObjectName(_fromUtf8("weaponSBox"))
        self.gridLayout.addWidget(self.weaponSBox, 3, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(cardSynthesis)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(cardSynthesis)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.weaponSSBox = QtGui.QSpinBox(cardSynthesis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weaponSSBox.sizePolicy().hasHeightForWidth())
        self.weaponSSBox.setSizePolicy(sizePolicy)
        self.weaponSSBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.weaponSSBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.weaponSSBox.setObjectName(_fromUtf8("weaponSSBox"))
        self.gridLayout.addWidget(self.weaponSSBox, 4, 1, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(cardSynthesis)
        self.pushButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout.addWidget(self.pushButton_5, 4, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_13 = QtGui.QLabel(cardSynthesis)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_3.addWidget(self.label_13)
        self.weaponExpRate = QtGui.QDoubleSpinBox(cardSynthesis)
        self.weaponExpRate.setDecimals(1)
        self.weaponExpRate.setSingleStep(0.1)
        self.weaponExpRate.setProperty("value", 1.0)
        self.weaponExpRate.setObjectName(_fromUtf8("weaponExpRate"))
        self.horizontalLayout_3.addWidget(self.weaponExpRate)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.weaponResetButton = QtGui.QPushButton(cardSynthesis)
        self.weaponResetButton.setObjectName(_fromUtf8("weaponResetButton"))
        self.horizontalLayout_5.addWidget(self.weaponResetButton)
        self.weaponRecipeButton = QtGui.QPushButton(cardSynthesis)
        self.weaponRecipeButton.setEnabled(True)
        self.weaponRecipeButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.weaponRecipeButton.setAutoDefault(False)
        self.weaponRecipeButton.setDefault(False)
        self.weaponRecipeButton.setObjectName(_fromUtf8("weaponRecipeButton"))
        self.horizontalLayout_5.addWidget(self.weaponRecipeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(cardSynthesis)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_7.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_7 = QtGui.QLabel(cardSynthesis)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.skillLevelBox = QtGui.QSpinBox(cardSynthesis)
        self.skillLevelBox.setMinimum(1)
        self.skillLevelBox.setObjectName(_fromUtf8("skillLevelBox"))
        self.horizontalLayout_2.addWidget(self.skillLevelBox)
        self.skillAtoBox = QtGui.QSpinBox(cardSynthesis)
        self.skillAtoBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.skillAtoBox.setSuffix(_fromUtf8(""))
        self.skillAtoBox.setMaximum(15000)
        self.skillAtoBox.setObjectName(_fromUtf8("skillAtoBox"))
        self.horizontalLayout_2.addWidget(self.skillAtoBox)
        self.skillRarityBox = QtGui.QComboBox(cardSynthesis)
        self.skillRarityBox.setObjectName(_fromUtf8("skillRarityBox"))
        self.skillRarityBox.addItem(_fromUtf8(""))
        self.skillRarityBox.addItem(_fromUtf8(""))
        self.skillRarityBox.addItem(_fromUtf8(""))
        self.skillRarityBox.addItem(_fromUtf8(""))
        self.skillRarityBox.addItem(_fromUtf8(""))
        self.skillRarityBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.skillRarityBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_8 = QtGui.QLabel(cardSynthesis)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.skillNBox = QtGui.QSpinBox(cardSynthesis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skillNBox.sizePolicy().hasHeightForWidth())
        self.skillNBox.setSizePolicy(sizePolicy)
        self.skillNBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.skillNBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.skillNBox.setObjectName(_fromUtf8("skillNBox"))
        self.gridLayout_2.addWidget(self.skillNBox, 0, 1, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(cardSynthesis)
        self.pushButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_2.addWidget(self.pushButton_6, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(cardSynthesis)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.skillRBox = QtGui.QSpinBox(cardSynthesis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skillRBox.sizePolicy().hasHeightForWidth())
        self.skillRBox.setSizePolicy(sizePolicy)
        self.skillRBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.skillRBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.skillRBox.setObjectName(_fromUtf8("skillRBox"))
        self.gridLayout_2.addWidget(self.skillRBox, 1, 1, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(cardSynthesis)
        self.pushButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_2.addWidget(self.pushButton_7, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(cardSynthesis)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.skillRRBox = QtGui.QSpinBox(cardSynthesis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skillRRBox.sizePolicy().hasHeightForWidth())
        self.skillRRBox.setSizePolicy(sizePolicy)
        self.skillRRBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.skillRRBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.skillRRBox.setObjectName(_fromUtf8("skillRRBox"))
        self.gridLayout_2.addWidget(self.skillRRBox, 2, 1, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(cardSynthesis)
        self.pushButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_2.addWidget(self.pushButton_8, 2, 2, 1, 1)
        self.label_11 = QtGui.QLabel(cardSynthesis)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.skillSBox = QtGui.QSpinBox(cardSynthesis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skillSBox.sizePolicy().hasHeightForWidth())
        self.skillSBox.setSizePolicy(sizePolicy)
        self.skillSBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.skillSBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.skillSBox.setObjectName(_fromUtf8("skillSBox"))
        self.gridLayout_2.addWidget(self.skillSBox, 3, 1, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(cardSynthesis)
        self.pushButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_2.addWidget(self.pushButton_9, 3, 2, 1, 1)
        self.label_12 = QtGui.QLabel(cardSynthesis)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.skillSSBox = QtGui.QSpinBox(cardSynthesis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skillSSBox.sizePolicy().hasHeightForWidth())
        self.skillSSBox.setSizePolicy(sizePolicy)
        self.skillSSBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.skillSSBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.skillSSBox.setObjectName(_fromUtf8("skillSSBox"))
        self.gridLayout_2.addWidget(self.skillSSBox, 4, 1, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(cardSynthesis)
        self.pushButton_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_10.setFlat(False)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_2.addWidget(self.pushButton_10, 4, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_14 = QtGui.QLabel(cardSynthesis)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_4.addWidget(self.label_14)
        self.skillExpRate = QtGui.QDoubleSpinBox(cardSynthesis)
        self.skillExpRate.setDecimals(1)
        self.skillExpRate.setSingleStep(0.1)
        self.skillExpRate.setProperty("value", 1.0)
        self.skillExpRate.setObjectName(_fromUtf8("skillExpRate"))
        self.horizontalLayout_4.addWidget(self.skillExpRate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.skillResetButton = QtGui.QPushButton(cardSynthesis)
        self.skillResetButton.setObjectName(_fromUtf8("skillResetButton"))
        self.horizontalLayout_6.addWidget(self.skillResetButton)
        self.skillRecipeButton = QtGui.QPushButton(cardSynthesis)
        self.skillRecipeButton.setEnabled(True)
        self.skillRecipeButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.skillRecipeButton.setAutoDefault(False)
        self.skillRecipeButton.setDefault(False)
        self.skillRecipeButton.setFlat(False)
        self.skillRecipeButton.setObjectName(_fromUtf8("skillRecipeButton"))
        self.horizontalLayout_6.addWidget(self.skillRecipeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.recipeTable = QtGui.QTableWidget(cardSynthesis)
        self.recipeTable.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.recipeTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.recipeTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.recipeTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.recipeTable.setObjectName(_fromUtf8("recipeTable"))
        self.recipeTable.setColumnCount(12)
        self.recipeTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(11, item)
        self.verticalLayout_3.addWidget(self.recipeTable)
        self.fuseButton = QtGui.QPushButton(cardSynthesis)
        self.fuseButton.setEnabled(False)
        self.fuseButton.setObjectName(_fromUtf8("fuseButton"))
        self.verticalLayout_3.addWidget(self.fuseButton)

        self.retranslateUi(cardSynthesis)
        self.weaponRarityBox.setCurrentIndex(4)
        self.skillRarityBox.setCurrentIndex(4)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.weaponNBox.stepUp)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.weaponRBox.stepUp)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), self.weaponRRBox.stepUp)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.weaponSBox.stepUp)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), self.weaponSSBox.stepUp)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.skillNBox.stepUp)
        QtCore.QObject.connect(self.pushButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), self.skillRBox.stepUp)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), self.skillRRBox.stepUp)
        QtCore.QObject.connect(self.pushButton_9, QtCore.SIGNAL(_fromUtf8("clicked()")), self.skillSBox.stepUp)
        QtCore.QObject.connect(self.pushButton_10, QtCore.SIGNAL(_fromUtf8("clicked()")), self.skillSSBox.stepUp)
        QtCore.QMetaObject.connectSlotsByName(cardSynthesis)
        cardSynthesis.setTabOrder(self.weaponLevelBox, self.weaponAtoBox)
        cardSynthesis.setTabOrder(self.weaponAtoBox, self.weaponRarityBox)
        cardSynthesis.setTabOrder(self.weaponRarityBox, self.weaponNBox)
        cardSynthesis.setTabOrder(self.weaponNBox, self.weaponRBox)
        cardSynthesis.setTabOrder(self.weaponRBox, self.weaponRRBox)
        cardSynthesis.setTabOrder(self.weaponRRBox, self.weaponSBox)
        cardSynthesis.setTabOrder(self.weaponSBox, self.weaponSSBox)
        cardSynthesis.setTabOrder(self.weaponSSBox, self.weaponExpRate)
        cardSynthesis.setTabOrder(self.weaponExpRate, self.weaponRecipeButton)
        cardSynthesis.setTabOrder(self.weaponRecipeButton, self.skillLevelBox)
        cardSynthesis.setTabOrder(self.skillLevelBox, self.skillAtoBox)
        cardSynthesis.setTabOrder(self.skillAtoBox, self.skillRarityBox)
        cardSynthesis.setTabOrder(self.skillRarityBox, self.skillNBox)
        cardSynthesis.setTabOrder(self.skillNBox, self.skillRBox)
        cardSynthesis.setTabOrder(self.skillRBox, self.skillRRBox)
        cardSynthesis.setTabOrder(self.skillRRBox, self.skillSBox)
        cardSynthesis.setTabOrder(self.skillSBox, self.skillSSBox)
        cardSynthesis.setTabOrder(self.skillSSBox, self.skillExpRate)
        cardSynthesis.setTabOrder(self.skillExpRate, self.skillRecipeButton)
        cardSynthesis.setTabOrder(self.skillRecipeButton, self.recipeTable)
        cardSynthesis.setTabOrder(self.recipeTable, self.fuseButton)

    def retranslateUi(self, cardSynthesis):
        cardSynthesis.setWindowTitle(QtGui.QApplication.translate("cardSynthesis", "Indirect Card Synthesis - Madoka Magica Online", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("cardSynthesis", "Weapon Base:", None, QtGui.QApplication.UnicodeUTF8))
        self.weaponLevelBox.setPrefix(QtGui.QApplication.translate("cardSynthesis", "lvl. ", None, QtGui.QApplication.UnicodeUTF8))
        self.weaponAtoBox.setPrefix(QtGui.QApplication.translate("cardSynthesis", "ato ", None, QtGui.QApplication.UnicodeUTF8))
        self.weaponRarityBox.setItemText(0, QtGui.QApplication.translate("cardSynthesis", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.weaponRarityBox.setItemText(1, QtGui.QApplication.translate("cardSynthesis", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.weaponRarityBox.setItemText(2, QtGui.QApplication.translate("cardSynthesis", "RR", None, QtGui.QApplication.UnicodeUTF8))
        self.weaponRarityBox.setItemText(3, QtGui.QApplication.translate("cardSynthesis", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.weaponRarityBox.setItemText(4, QtGui.QApplication.translate("cardSynthesis", "SS", None, QtGui.QApplication.UnicodeUTF8))
        self.weaponRarityBox.setItemText(5, QtGui.QApplication.translate("cardSynthesis", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("cardSynthesis", "N:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("cardSynthesis", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("cardSynthesis", "R:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("cardSynthesis", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("cardSynthesis", "RR:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("cardSynthesis", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("cardSynthesis", "S:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("cardSynthesis", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("cardSynthesis", "SS:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("cardSynthesis", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("cardSynthesis", "Fusion Exp Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.weaponExpRate.setSuffix(QtGui.QApplication.translate("cardSynthesis", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.weaponResetButton.setText(QtGui.QApplication.translate("cardSynthesis", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.weaponRecipeButton.setText(QtGui.QApplication.translate("cardSynthesis", "Weapon Recipes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("cardSynthesis", "Skill Base:", None, QtGui.QApplication.UnicodeUTF8))
        self.skillLevelBox.setPrefix(QtGui.QApplication.translate("cardSynthesis", "lvl. ", None, QtGui.QApplication.UnicodeUTF8))
        self.skillAtoBox.setPrefix(QtGui.QApplication.translate("cardSynthesis", "ato ", None, QtGui.QApplication.UnicodeUTF8))
        self.skillRarityBox.setItemText(0, QtGui.QApplication.translate("cardSynthesis", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.skillRarityBox.setItemText(1, QtGui.QApplication.translate("cardSynthesis", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.skillRarityBox.setItemText(2, QtGui.QApplication.translate("cardSynthesis", "RR", None, QtGui.QApplication.UnicodeUTF8))
        self.skillRarityBox.setItemText(3, QtGui.QApplication.translate("cardSynthesis", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.skillRarityBox.setItemText(4, QtGui.QApplication.translate("cardSynthesis", "SS", None, QtGui.QApplication.UnicodeUTF8))
        self.skillRarityBox.setItemText(5, QtGui.QApplication.translate("cardSynthesis", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("cardSynthesis", "N:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("cardSynthesis", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("cardSynthesis", "R:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("cardSynthesis", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("cardSynthesis", "RR:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("cardSynthesis", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("cardSynthesis", "S:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("cardSynthesis", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("cardSynthesis", "SS:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("cardSynthesis", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("cardSynthesis", "Fusion Exp Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.skillExpRate.setSuffix(QtGui.QApplication.translate("cardSynthesis", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.skillResetButton.setText(QtGui.QApplication.translate("cardSynthesis", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.skillRecipeButton.setText(QtGui.QApplication.translate("cardSynthesis", "Skill Recipes", None, QtGui.QApplication.UnicodeUTF8))
        self.recipeTable.setSortingEnabled(True)
        item = self.recipeTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("cardSynthesis", "Recipe", None, QtGui.QApplication.UnicodeUTF8))
        item = self.recipeTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("cardSynthesis", "Exp per Coin", None, QtGui.QApplication.UnicodeUTF8))
        item = self.recipeTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("cardSynthesis", "Exp Efficiency", None, QtGui.QApplication.UnicodeUTF8))
        item = self.recipeTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("cardSynthesis", "Exp to Base", None, QtGui.QApplication.UnicodeUTF8))
        item = self.recipeTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("cardSynthesis", "Total Cost", None, QtGui.QApplication.UnicodeUTF8))
        item = self.recipeTable.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("cardSynthesis", "Final Level", None, QtGui.QApplication.UnicodeUTF8))
        item = self.recipeTable.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("cardSynthesis", "Final Ato", None, QtGui.QApplication.UnicodeUTF8))
        item = self.recipeTable.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("cardSynthesis", "N", None, QtGui.QApplication.UnicodeUTF8))
        item = self.recipeTable.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("cardSynthesis", "R", None, QtGui.QApplication.UnicodeUTF8))
        item = self.recipeTable.horizontalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("cardSynthesis", "RR", None, QtGui.QApplication.UnicodeUTF8))
        item = self.recipeTable.horizontalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("cardSynthesis", "S", None, QtGui.QApplication.UnicodeUTF8))
        item = self.recipeTable.horizontalHeaderItem(11)
        item.setText(QtGui.QApplication.translate("cardSynthesis", "SS", None, QtGui.QApplication.UnicodeUTF8))
        self.fuseButton.setText(QtGui.QApplication.translate("cardSynthesis", "Fuse to Base", None, QtGui.QApplication.UnicodeUTF8))

